export const clients = [
    {
        fname: "Aslam",
        lname: "Butt",
        userName: "aslam.butt",
        password: "aslam@123",
        phoneNo: "+920139123912",
        email: "email@email.com",
    },
    {
        fname: "Farida",
        lname: "Khan",
        userName: "farida.khan",
        password: "farida@456",
        phoneNo: "+920139123912",
        email: "email@email.com",
    },
    {
        fname: "Nadeem",
        lname: "Malik",
        userName: "nadeem.malik",
        password: "nadeem@789",
        phoneNo: "+920139123912",
        email: "email@email.com",
    },
    {
        fname: "Saima",
        lname: "Akhtar",
        userName: "saima.akhtar",
        password: "saima@987",
        phoneNo: "+920139123912",
        email: "email@email.com",
    },
    {
        fname: "Usman",
        lname: "Ahmed",
        userName: "usman.ahmed",
        password: "usman@654",
        phoneNo: "+920139123912",
        email: "email@email.com",
    },
];

export const employees = [
    {
        fname: "Aslam",
        lname: "Butt",
        role: "employee",
        department: "Color Matching",
        date: "20-02-2010",
        userName: "aslam.butt",
        password: "aslam@123",
    },
    {
        fname: "Farida",
        lname: "Khan",
        role: "head",
        department: "Measurements",
        date: "15-06-2015",
        userName: "farida.khan",
        password: "farida@456",
    },
    {
        fname: "Nadeem",
        lname: "Malik",
        role: "employee",
        department: "Color Matching",
        date: "03-11-2018",
        userName: "nadeem.malik",
        password: "nadeem@789",
    },
    {
        fname: "Saima",
        lname: "Akhtar",
        role: "employee",
        department: "Measurements",
        date: "12-09-2012",
        userName: "saima.akhtar",
        password: "saima@987",
    },
    {
        fname: "Usman",
        lname: "Ahmed",
        role: "head",
        department: "Color Matching",
        date: "08-04-2017",
        userName: "usman.ahmed",
        password: "usman@654",
    },
    {
        fname: "Ayesha",
        lname: "Riaz",
        role: "employee",
        department: "Measurements",
        date: "23-01-2019",
        userName: "ayesha.riaz",
        password: "ayesha@321",
    },
    {
        fname: "Imran",
        lname: "Zafar",
        role: "head",
        department: "Color Matching",
        date: "10-07-2014",
        userName: "imran.zafar",
        password: "imran@135",
    },
    {
        fname: "Nazia",
        lname: "Iqbal",
        role: "employee",
        department: "Color Matching",
        date: "05-12-2016",
        userName: "nazia.iqbal",
        password: "nazia@246",
    },
    {
        fname: "Kamran",
        lname: "Akram",
        role: "employee",
        department: "Measurements",
        date: "18-03-2021",
        userName: "kamran.akram",
        password: "kamran@789",
    },
    {
        fname: "Saba",
        lname: "Hussain",
        role: "head",
        department: "Measurements",
        date: "30-08-2013",
        userName: "saba.hussain",
        password: "saba@567",
    },
];

export const colorMatchingActive = {
    title: "Color Matching",
    batchNo: 5,
    progressVal: 45,
    tableItems: [
        {
            name: "Batch 4",
            date: "23/02/2024",
            progress: 65,
        },
        {
            name: "Batch 3",
            date: "20/02/2024",
            progress: 90,
        },
        {
            name: "Batch 2",
            date: "15/01/2024",
            progress: 100,
        },
    ]
}
export const measurementsActive = {
    title: "Measurements",
    batchNo: 15,
    progressVal: 55,
    tableItems: [
        {
            name: "Batch 14",
            date: "23/02/2024",
            progress: 45,
        },
        {
            name: "Batch 13",
            date: "20/02/2024",
            progress: 60,
        },
        {
            name: "Batch 12",
            date: "15/01/2024",
            progress: 90,
        },
    ]
}